GET http://localhost:3001/api/devices/
###
POST http://localhost:3001/api/devices/ HTTP/1.1
content-type: application/json

{
    "uid": "09122132189",
    "vendor": "TP Link",
    "status": true,
    "gateway": "623392897a3232f4cca8a975"
}
###
PUT http://localhost:3001/api/devices/623394b128342a590cb973cc HTTP/1.1
content-type: application/json

{
    "uid": "09122132123",
    "vendor": "TP Link",
    "status": false
}
###
DELETE  http://localhost:3001/api/devices/6233963428342a590cb973e4 HTTP/1.1